### ISSUE TITLE
Pers_in_visit too many files open

### ISSUE THREAD

**Issue by Vb2341** [mgennaro/short_term_persistence#3]
When attempting to multiprocess the extraction pixels from the IMA reads, an OSError is raised saying there are too many files open- even though it seems that there are no files open, and everything is already in memory.

**Comment by mgennaro** [comment]
The problem resided in that the pool object was being (re-)created inside a loop. Initializing the object outside the pool are reusing the same workers solved it.
Got the idea from here:
**https://stackoverflow.com/questions/36596805/python-multiprocessing-claims-too-many-open-files-when-no-files-are-even-opened**
